version: '3'

services:
  app:
    build:
      context: "./php"

  nginx:
    image: nginx:latest
    #build:
    #  context: "./nginx"
    volumes:
      #- ./nginx/var/www:/var/www
      - ./nginx/default.nginx:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
      - ../:var/www/html/
    #ports:
    #  - "80:80"
    depends_on:
      - php
    #links:
    #  - php
    networks:
      - frontend
      - backend
  php:
    build:
      context: "./php"
    volumes:
      - ../:/var/www/html/
    depends_on:
      - mysql
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "REDIS_PORT=6379"
      - "REDIS_HOST=redis"
    links:
      - mysql
    networks:
      - backend

  mysql:
    build:
      context: "./mysql"
    volumes:
      - ./mysql/storage/docker/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=''"
      - "MYSQL_DATABASE=paveladmin"
    networks:
      - backend

  phpmyadmin:
    build:
      context: "./phpmyadmin"
    volumes:
      - ./phpmyadmin/var/www:/var/www
    environment:
      - VIRTUAL_HOST=phpmyadmin.local
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    networks:
      - frontend
      - backend

networks:
  frontend:
    external:
      name: proxy_proxy
  backend: